### ISSUE TITLE
Erro ao realizar o makemigrations ou migrate

### ISSUE THREAD

**Issue by GuiAFO** [rg3915/estoque#81]
Ao solicitar o makemigrations aparece o seguinte erro:

```
Traceback (most recent call last):
  File "C:\estoque\.venv\Lib\site-packages\django\apps\config.py", line 210, in create
    app_module = import_module(app_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\estoque\manage.py", line 22, in <module>
    main()
  File "C:\estoque\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\estoque\.venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\estoque\.venv\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\estoque\.venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\estoque\.venv\Lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\estoque\.venv\Lib\site-packages\django\apps\config.py", line 212, in create
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Cannot import 'core'. Check that 'projeto.core.apps.CoreConfig.name' is correct.``
```

**Comment by rg3915** [comment]
@GuiAFO qual versão do Django você está usando?
Me manda o link do Github do seu projeto pra eu ver.

**Comment by GuiAFO** [comment]
Django 4.2

**Comment by rg3915** [comment]
@GuiAFO Resolvido:

Edite

```python
# core/apps.py
name = 'projeto.core'
```

```python
# produto/apps.py
name = 'projeto.produto'
```
